version: "3.3"

services:

  worker:
    build:
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    runtime: nvidia
